### ISSUE TITLE
Simplify index tracking

### ISSUE THREAD

**Issue by apozharski** [nurkanovic/nosnoc#69]
Currently indexes are tracked independently at different levels and must be handled somewhat manually. 
Several things need to be done to make maintenance of NOSNOC easier:
- Remove `FiniteElement` and `ControlStage` classes
- Use a smarter index tracking utility to avoid  pre-definition, etc. Something similar to CasADi "structures" in `casadi.tools`

**Comment by nurkanovic** [comment]
@apozharski  done?

**Comment by apozharski** [comment]
I would say with the `vdx` based design now in a decent state I would say so.
